teams:
  - name: acapy-admins
    maintainers:
      - swcurran
    members:
      - WadeBarnes
      - TimoGlastra
      - andrewwhitehead
      - dbluhm
  - name: acapy-committers
    maintainers:
      - swcurran
    members:
      - andrewwhitehead
      - TimoGlastra
      - WadeBarnes
      - amanji
      - chumbert
      - dbluhm
      - esune
      - ianco
      - jamshale
      - ff137
      - thiagoromanos
      - PatStLouis
      - loneil
  - name: acapy-contributors
    maintainers:
      - swcurran
    members:
      - WadeBarnes
      - Jsyro
      - dbluhm
      - esune
      - ianco
      - jamshale
      - TheTechmage
      - loneil
      - Gavinok
  - name: askar-admins
    maintainers:
      - andrewwhitehead
    members:
      - TimoGlastra
      - WadeBarnes
      - swcurran
  - name: askar-maintainers
    maintainers:
      - andrewwhitehead
    members:
      - berendsliedrecht
      - genaris
  - name: askar-wrapper-javascript-admins
    maintainers:
      - TimoGlastra
    members:
      - andrewwhitehead
      - swcurran
  - name: askar-wrapper-javascript-maintainers
    maintainers:
      - TimoGlastra
    members:
      - cvarjao
      - berendsliedrecht
      - genaris
  - name: architecture-sig-maintainers
    maintainers:
      - tkuhrt
  - name: bifold-wallet-admins
    maintainers:
      - jleach
      - cvarjao
      - bryce-mcmath
  - name: bifold-wallet-maintainers
    maintainers:
      - jleach
      - bryce-mcmath
      - al-rosenthal
    members:
      - amanji
      - cvarjao
      - fc-santos
      - jcdrouin21
      - MosCD3
      - thiagoromanos
  - name: bots
    maintainers:
      - ryjones
    members:
      - owf-bot
  - name: credo-admins
    maintainers:
      - TimoGlastra
  - name: credo-maintainers
    maintainers:
      - jakubkoci
      - TimoGlastra
    members:
      - berendsliedrecht
      - genaris
      - auer-martin
  - name: didcomm-mediator-credo-admin
    maintainers:
      - TimoGlastra
      - jleach
  - name: didcomm-mediator-credo-maintainers
    maintainers:
      - jleach
      - TimoGlastra
    members:
      - sairanjit
      - genaris
      - GHkrishna
      - bryce-mcmath
      - al-rosenthal
      - esune
      - jamshale
      - loneil
      - cvarjao
  - name: didcomm-admins
    maintainers:
      - dbluhm
    members:
      - WadeBarnes
      - TimoGlastra
      - andrewwhitehead
      - swcurran
  - name: didcomm-committers
    maintainers:
      - swcurran
    members:
      - andrewwhitehead
      - TimoGlastra
      - WadeBarnes
      - dbluhm
      - esune
      - ianco
      - jamshale
      - TheTechmage
  - name: didcomm-contributors
    maintainers:
      - swcurran
    members:
      - WadeBarnes
      - dbluhm
      - esune
      - ianco
      - jamshale
  - name: digital-wallet-and-agent-overviews-sig-maintainers
    maintainers:
      - cre8
    members:
      - samuelmr
  - name: digital-wallet-and-agent-overviews-sig-admins
    maintainers:
      - cre8
  - name: helm-charts-admins
    maintainers:
      - esune
    members:
      - WadeBarnes
      - swcurran
      - i5okie
  - name: lf-employees
    maintainers:
      - ryjones
    members:
      - SeanBohan
  - name: owl-agent-test-harness-admins
    maintainers:
      - nodlesh
      - swcurran
  - name: owl-agent-test-harness-committers
    maintainers:
      - swcurran
      - PatStLouis
    members:
      - AmarjeetAkv
      - jamshale
      - gmulhearn
      - genaris
      - Patrik-Stas
      - WadeBarnes
      - usingtechnology
      - mirgee
      - Jsyro
      - lauravuo
      - tdiesler
      - ianco
      - nodlesh
  - name: owl-akrida-admins
    maintainers:
      - KimEbert42
    members:
      - swcurran
      - nodlesh
  - name: owl-akrida-committers
    maintainers:
      - KimEbert42
    members:
      - nodlesh
      - AmarjeetAkv
      - anwalker293
      - loneil
      - GHkrishna
      - dbluhm
  - name: owl-mobile-wallet-test-harness-admins
    maintainers:
      - nodlesh
      - al-rosenthal
  - name: owl-mobile-wallet-test-harness-committers
    maintainers:
      - nodlesh
      - al-rosenthal
    members:
      - AmarjeetAkv
  - name: safe-wallet-sig-maintainers
    maintainers:
      - tkuhrt
    members:
      - skounis
      - darrellodonnell
  - name: sd-jwt-js-admin
    maintainers:
      - cre8
    members:
      - lukasjhan
  - name: sd-jwt-js-maintainers
    maintainers:
      - cre8
    members:
      - aceshim
      - berendsliedrecht
      - lukasjhan
      - zustkeeper
  - name: tac
    maintainers:
      - skounis
    members:
      - davidz25
      - rolsonquadras
      - stefan-kauhaus
      - aceshim
      - swcurran
      - wenjing
  - name: vcx-maintainers
    maintainers:
      - gmulhearn
    members:
      - gmulhearn
      - dc-anon
repositories:
  - name: .github
    teams:
      tac: maintain
    visibility: public
  - name: acapy
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-plugins
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-controllers
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-tools
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-endorser-service
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
    visibility: public
  - name: acapy-vc-authn-oidc
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: triage
    visibility: public
  - name: askar
    teams:
      askar-admins: admin
      askar-maintainers: maintain
  - name: askar-wrapper-javascript
    teams:
      askar-wrapper-javascript-admins: admin
      askar-admins: admin
      askar-wrapper-javascript-maintainers: maintain
      askar-maintainers: maintain
  - name: architecture-sig
    teams:
      architecture-sig-maintainers: maintain
    visibility: public
  - name: bifold-wallet
    teams:
      bifold-wallet-admins: admin
      bifold-wallet-maintainers: maintain
    visibility: public
  - name: credo-ts
    teams:
      credo-admins: admin
      credo-maintainers: maintain
    visibility: public
  - name: credo-ts-docs
    teams:
      credo-admins: admin
      credo-maintainers: maintain
    visibility: public
  - name: credo-ts-ext
    teams:
      credo-admins: admin
      credo-maintainers: maintain
    visibility: public
  - name: didcomm-mediator-service
    teams:
      didcomm-admins: admin
      didcomm-committers: maintain
      didcomm-contributors: read
    visibility: public
  - name: didcomm-mediator-credo
    teams:
      credo-admins: admin
      credo-maintainers: maintain
      didcomm-mediator-credo-maintainers: maintain
      didcomm-mediator-credo-admin: admin
      didcomm-committers: write
    visibility: public
  - name: didcomm-mediator-socketdock
    teams:
      didcomm-admins: admin
      didcomm-committers: maintain
      didcomm-contributors: read
    visibility: public
  - name: digital-wallet-and-agent-overviews-sig
    teams:
      digital-wallet-and-agent-overviews-sig-admins: admin
      digital-wallet-and-agent-overviews-sig-maintainers: maintain
    visibility: public
  - name: governance
    teams:
      tac: maintain
    visibility: public
  - name: helm-charts
    teams:
      tac: maintain
      helm-charts-admins: admin
    visibility: public
  - name: openwallet-foundation-landscape
    visibility: private
  - name: owl
    teams:
      owl-mobile-wallet-test-harness-admins: admin
      owl-mobile-wallet-test-harness-committers: triage
      owl-agent-test-harness-admins: admin
      owl-agent-test-harness-committers: triage
      owl-akrida-admins: admin
      owl-akrida-committers: triage
    visibility: public
  - name: owl-mobile-wallet-test-harness
    teams:
      bifold-wallet-admins: admin
      bifold-wallet-maintainers: maintain
      owl-mobile-wallet-test-harness-admins: admin
      owl-mobile-wallet-test-harness-committers: maintain
    visibility: public
  - name: project-proposals
    teams:
      tac: maintain
    visibility: public
  - name: safe-wallet-sig
    teams:
      safe-wallet-sig-maintainers: maintain
    visibility: public
  - name: sd-jwt-js
    teams:
      sd-jwt-js-maintainers: maintain
      sd-jwt-js-admin: admin
    visibility: public
  - name: tac
    teams:
      tac: maintain
    visibility: public
  - name: owl-agent-test-harness
    teams:
      acapy-committers: maintain
      credo-maintainers: maintain
      bots: maintain
      owl-agent-test-harness-admins: admin
      owl-agent-test-harness-committers: maintain
    visibility: public
  - name: owl-akrida
    teams:
      acapy-committers: maintain
      credo-maintainers: maintain
      owl-akrida-admins: admin
      owl-akrida-committers: maintain
    visibility: public
  - name: vcx
    teams:
      vcx-maintainers: maintain
      bots: maintain
    visibility: public
