teams:
  - name: acapy-admins
    maintainers:
      - swcurran
    members:
      - WadeBarnes
      - TimoGlastra
      - andrewwhitehead
      - dbluhm
  - name: acapy-committers
    maintainers:
      - swcurran
    members:
      - andrewwhitehead
      - TimoGlastra
      - WadeBarnes
      - amanji
      - chumbert
      - dbluhm
      - esune
      - ianco
      - jamshale
      - ff137
      - thiagoromanos
      - PatStLouis
      - loneil
      - Gavinok
  - name: acapy-contributors
    maintainers:
      - swcurran
    members:
      - WadeBarnes
      - Jsyro
      - dbluhm
      - esune
      - ianco
      - jamshale
      - TheTechmage
      - loneil
      - Gavinok
  - name: acapy-me-maintainers
    maintainers:
      - swcurran
    members:
      - Athan13
      - dbluhm
      - esune
  - name: askar-admins
    maintainers:
      - andrewwhitehead
    members:
      - TimoGlastra
      - WadeBarnes
      - swcurran
  - name: askar-maintainers
    maintainers:
      - andrewwhitehead
    members:
      - berendsliedrecht
      - genaris
  - name: askar-wrapper-javascript-admins
    maintainers:
      - TimoGlastra
    members:
      - andrewwhitehead
      - swcurran
  - name: askar-wrapper-javascript-maintainers
    maintainers:
      - TimoGlastra
    members:
      - cvarjao
      - berendsliedrecht
      - genaris
#  - name: architecture-sig-maintainers
#    maintainers:
#      - ryjones
  - name: bifold-wallet-admins
    maintainers:
      - jleach
      - cvarjao
      - bryce-mcmath
  - name: bifold-wallet-maintainers
    maintainers:
      - jleach
      - bryce-mcmath
      - al-rosenthal
    members:
      - amanji
      - cvarjao
      - fc-santos
      - jcdrouin21
      - MacDeluca
      - MosCD3
      - thiagoromanos
  - name: bots
    maintainers:
      - ryjones
    members:
      - owf-bot
  - name: credo-admins
    maintainers:
      - TimoGlastra
  - name: credo-maintainers
    maintainers:
      - jakubkoci
      - TimoGlastra
    members:
      - auer-martin
      - berendsliedrecht
      - genaris
      - hacdias
  - name: didcomm-mediator-credo-admin
    maintainers:
      - TimoGlastra
      - jleach
  - name: didcomm-mediator-credo-maintainers
    maintainers:
      - jleach
      - TimoGlastra
    members:
      - sairanjit
      - genaris
      - GHkrishna
      - bryce-mcmath
      - al-rosenthal
      - esune
      - jamshale
      - loneil
      - cvarjao
  - name: didcomm-admins
    maintainers:
      - dbluhm
    members:
      - WadeBarnes
      - TimoGlastra
      - andrewwhitehead
      - swcurran
  - name: didcomm-committers
    maintainers:
      - swcurran
    members:
      - andrewwhitehead
      - TimoGlastra
      - WadeBarnes
      - dbluhm
      - esune
      - ianco
      - jamshale
      - TheTechmage
  - name: didcomm-contributors
    maintainers:
      - swcurran
    members:
      - WadeBarnes
      - dbluhm
      - esune
      - ianco
      - jamshale
  - name: digital-wallet-and-agent-overviews-sig-maintainers
    maintainers:
      - cre8
    members:
      - samuelmr
  - name: digital-wallet-and-agent-overviews-sig-admins
    maintainers:
      - cre8
  - name: helm-charts-admins
    maintainers:
      - esune
    members:
      - WadeBarnes
      - swcurran
      - i5okie
  - name: lf-employees
    maintainers:
      - ryjones
    members:
      - SeanBohan
  - name: multipaz-admins
    maintainers:
      - davidz25
    members:
      - troykensinger
  - name: multipaz-developer-website-maintainers
    maintainers:
      - davidz25
    members:
      - dzuluaga
      - VishnuSanal
      - itsme291
      - hanluOMH
  - name: multipaz-maintainers
    maintainers:
      - davidz25
    members:
      - 15characterlimi
      - koukarine
      - dyiop
      - GarethCOliver
      - sethmoo
      - sorotokin
      - suzannajiwani
      - troykensinger
      - kdeus
      - hzawawy
      - TheCoryBarker
      - jaredkidd
  - name: multipaz-team
    maintainers:
      - davidz25
    members:
      - dzuluaga
      - VishnuSanal
      - itsme291
      - hanluOMH
  - name: owl-agent-test-harness-admins
    maintainers:
      - nodlesh
      - swcurran
  - name: owl-agent-test-harness-committers
    maintainers:
      - swcurran
      - PatStLouis
    members:
      - AmarjeetAkv
      - jamshale
      - gmulhearn
      - genaris
      - WadeBarnes
      - usingtechnology
      - mirgee
      - Jsyro
      - lauravuo
      - tdiesler
      - ianco
      - nodlesh
  - name: owl-akrida-admins
    maintainers:
      - KimEbert42
    members:
      - swcurran
      - nodlesh
  - name: owl-akrida-committers
    maintainers:
      - KimEbert42
    members:
      - nodlesh
      - AmarjeetAkv
      - anwalker293
      - loneil
      - GHkrishna
      - dbluhm
  - name: owl-mobile-wallet-test-harness-admins
    maintainers:
      - nodlesh
      - al-rosenthal
  - name: owl-mobile-wallet-test-harness-committers
    maintainers:
      - nodlesh
      - al-rosenthal
    members:
      - AmarjeetAkv
  - name: safe-wallet-sig-maintainers
    maintainers:
      - skounis
    members:
      - darrellodonnell
  - name: sd-jwt-js-admin
    maintainers:
      - cre8
    members:
      - lukasjhan
  - name: sd-jwt-js-maintainers
    maintainers:
      - cre8
    members:
      - aceshim
      - berendsliedrecht
      - lukasjhan
      - zustkeeper
  - name: security-managers
    maintainers:
      - SeanBohan
      - ryjones
  - name: tac
    maintainers:
      - skounis
    members:
      - davidz25
      - rolsonquadras
      - stefan-kauhaus
      - aceshim
      - swcurran
      - wenjing
  - name: vcx-maintainers
    maintainers:
      - gmulhearn
    members:
      - dc-anon
repositories:
  - name: .github
    teams:
      security-managers: read
      tac: maintain
    visibility: public
  - name: acapy
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
      security-managers: read
    visibility: public
  - name: acapy-plugins
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
      security-managers: read
    visibility: public
  - name: acapy-controllers
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
      security-managers: read
    visibility: public
  - name: acapy-minimal-example
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
      acapy-me-maintainers: maintain
      security-managers: read
    visibility: public
  - name: acapy-tools
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
      security-managers: read
    visibility: public
  - name: acapy-endorser-service
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: read
      security-managers: read
    visibility: public
  - name: acapy-vc-authn-oidc
    teams:
      acapy-admins: admin
      acapy-committers: maintain
      acapy-contributors: triage
      security-managers: read
    visibility: public
  - name: askar
    teams:
      askar-admins: admin
      askar-maintainers: maintain
      security-managers: read
  - name: askar-wrapper-javascript
    teams:
      askar-wrapper-javascript-admins: admin
      askar-admins: admin
      askar-wrapper-javascript-maintainers: maintain
      askar-maintainers: maintain
      security-managers: read
    visibility: public
#  - name: architecture-sig
#    teams:
#      architecture-sig-maintainers: maintain
#    visibility: public
  - name: bifold-wallet
    teams:
      bifold-wallet-admins: admin
      bifold-wallet-maintainers: maintain
      security-managers: read
    visibility: public
  - name: credo-ts
    teams:
      credo-admins: admin
      credo-maintainers: maintain
      security-managers: read
    visibility: public
  - name: credo-ts-docs
    teams:
      credo-admins: admin
      credo-maintainers: maintain
      security-managers: read
    visibility: public
  - name: credo-ts-ext
    teams:
      credo-admins: admin
      credo-maintainers: maintain
      security-managers: read
    visibility: public
  - name: didcomm-mediator-service
    teams:
      didcomm-admins: admin
      didcomm-committers: maintain
      didcomm-contributors: read
      security-managers: read
    visibility: public
  - name: didcomm-mediator-credo
    teams:
      credo-admins: admin
      credo-maintainers: maintain
      didcomm-mediator-credo-maintainers: maintain
      didcomm-mediator-credo-admin: admin
      didcomm-committers: write
      security-managers: read
    visibility: public
  - name: didcomm-mediator-socketdock
    teams:
      didcomm-admins: admin
      didcomm-committers: maintain
      didcomm-contributors: read
      security-managers: read
    visibility: public
  - name: digital-wallet-and-agent-overviews-sig
    teams:
      digital-wallet-and-agent-overviews-sig-admins: admin
      digital-wallet-and-agent-overviews-sig-maintainers: maintain
      security-managers: read
    visibility: public
  - name: governance
    teams:
      security-managers: read
      tac: maintain
    visibility: public
  - name: helm-charts
    teams:
      helm-charts-admins: admin
      security-managers: read
      tac: maintain
    visibility: public
  - name: multipaz
    teams:
      multipaz-admins: admin
      multipaz-maintainers: maintain
      multipaz-team: triage
      security-managers: read
    visibility: public
  - name: multipaz-extras
    teams:
      multipaz-admins: admin
      multipaz-maintainers: maintain
      multipaz-team: triage
      security-managers: read
    visibility: public
  - name: multipaz-samples
    teams:
      multipaz-admins: admin
      multipaz-maintainers: maintain
      multipaz-developer-website-maintainers: maintain
      multipaz-team: triage
      security-managers: read
    visibility: public
  - name: multipaz-identity-reader
    teams:
      multipaz-admins: admin
      multipaz-maintainers: maintain
      multipaz-team: triage
      security-managers: read
    visibility: public
  - name: multipaz-developer-website
    teams:
      multipaz-admins: admin
      multipaz-developer-website-maintainers: maintain
      multipaz-maintainers: maintain
      multipaz-team: triage
      security-managers: read
    visibility: public
  - name: openwallet-foundation-landscape
    visibility: private
  - name: owl
    teams:
      owl-mobile-wallet-test-harness-admins: admin
      owl-mobile-wallet-test-harness-committers: triage
      owl-agent-test-harness-admins: admin
      owl-agent-test-harness-committers: triage
      owl-akrida-admins: admin
      owl-akrida-committers: triage
      security-managers: read
    visibility: public
  - name: owl-mobile-wallet-test-harness
    teams:
      bifold-wallet-admins: admin
      bifold-wallet-maintainers: maintain
      owl-mobile-wallet-test-harness-admins: admin
      owl-mobile-wallet-test-harness-committers: maintain
      security-managers: read
    visibility: public
  - name: project-proposals
    teams:
      security-managers: read
      tac: maintain
    visibility: public
  - name: safe-wallet-sig
    teams:
      safe-wallet-sig-maintainers: maintain
      security-managers: read
    visibility: public
  - name: sd-jwt-js
    teams:
      sd-jwt-js-maintainers: maintain
      sd-jwt-js-admin: admin
      security-managers: read
    visibility: public
  - name: tac
    teams:
      security-managers: read
      tac: maintain
    visibility: public
  - name: owl-agent-test-harness
    teams:
      acapy-committers: maintain
      bots: maintain
      credo-maintainers: maintain
      owl-agent-test-harness-admins: admin
      owl-agent-test-harness-committers: maintain
      security-managers: read
    visibility: public
  - name: owl-akrida
    teams:
      acapy-committers: maintain
      credo-maintainers: maintain
      owl-akrida-admins: admin
      owl-akrida-committers: maintain
      security-managers: read
    visibility: public
  - name: vcx
    teams:
      bots: maintain
      security-managers: read
      vcx-maintainers: maintain
    visibility: public
